apiVersion: v1
kind: Service
metadata:
  namespace: probes
  name: dns-propagation-prober
  labels:
    probe: dns-propagation-prober
spec:
  ports:
    - name: metrics
      port: 8080
  selector:
    probe: dns-propagation-prober
