apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Name}}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{.Namespace}}
roleRef:
  kind: ClusterRole
  name: list-clusterrole-0
  apiGroup: rbac.authorization.k8s.io
