{{$bytes := .bytes}}
{{$group := DefaultParam .group .Name}}

apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
  labels:
    group: {{$group}}
type: Opaque
stringData:
  password: {{RandData $bytes}}
